# from itertools import product

# import numpy as np


# # ============================================================
# # Global simulation constants
# # ============================================================

# INIT_MOTHERS = 15   # matches root Config and all evolutionary phases (Phase 3+)
# INITIAL_ENERGY = 1.0    # matches root Config (Change J): full energy at birth

# VALIDATION_SEEDS = list(range(42, 47))
# DEFAULT_SWEEP_SEED_BASE = 42000
# DEFAULT_PERCEPTION_RADIUS = 15.0
# TAIL_WINDOW = 200


# # ============================================================
# # Plot switches
# # ============================================================

# # Main validation plot is always generated by run.py.
# # These switches control additional diagnostic plots.

# PLOT_SMOOTH_WINDOW = 25

# ENABLE_ACTION_SELECTION_PLOT = True
# ENABLE_MOTIVATION_SELECTION_PLOT = True
# ENABLE_FAILED_SELECTION_PLOT = True

# # 1) Stacked area chart of realized actions + failed selections.
# ENABLE_STACKED_ACTION_FAILED_PLOT = True

# # 2) Correlation plot: FAILED_SELF / FAILED_FORAGE vs energy decay.
# # Correlation plot for FAILED_FORAGE only.
# # FAILED_SELF is not useful in Phase 2 because SELF always falls back to REST.
# ENABLE_FAILED_FORAGE_ENERGY_CORRELATION_PLOT = True
# ENABLE_FAILED_SELF_ENERGY_CORRELATION_PLOT = False

# # Diagnostic plot to verify whether action/motivation rates sum to 1.
# ENABLE_RATE_SUM_CHECK_PLOT = True

# # 3) State-space scatter: Energy vs action/motivation rate.
# ENABLE_STATE_SPACE_ENERGY_ACTION_PLOT = True

# # 4) Food consumption / pick-eat behavior over time.
# ENABLE_FOOD_CONSUMPTION_PLOT = True

# # 5) Spatial heatmap of mother population.
# ENABLE_SPATIAL_HEATMAP_PLOT = True

# # 6) Energy loss/gain breakdown.
# ENABLE_ENERGY_EXPENDITURE_PLOT = True

# # 7) Homeostatic balance plot: Energy vs Fatigue.
# ENABLE_HOMEOSTATIC_BALANCE_PLOT = True


# # ============================================================
# # Baseline genome weights
# # ============================================================

# # Phase 2 uses the unified MotherAgent decision interface:
# #   environmental cue × genome weight → softmax motivation
# #
# # For Phase 2 survival-minimal:
# #   - CARE is disabled
# #   - FORAGE and SELF are neutral baseline weights
# #
# # This keeps Phase 2 as an ecological survival baseline, not an evolved
# # behavioral baseline.
# BASELINE_GENOME_WEIGHTS = {
#     "care_weight": 0.0,
#     "forage_weight": 1.0,
#     "self_weight": 1.0,
# }


# # ============================================================
# # Balanced baseline used as reference for sensitivity sweep
# # ============================================================

# BALANCED_BASELINE = {
#     "perception_radius": DEFAULT_PERCEPTION_RADIUS,
#     # hunger_rate is LOCKED at 1/35 by starvation constraint (LOGIC.md Change J).
#     # Not a free parameter — adult starves in 35 ticks = 7 days (5 ticks/day).
#     "hunger_rate": 1 / 35,
#     "move_cost": 0.001,
#     # eat_gain rescaled from 0.07 (for old hunger_rate=0.005) → 0.25 (root Config default).
#     # Ratio: one food = eat_gain / hunger_rate ticks of energy.
#     # 0.25 / 0.0286 ≈ 8.7 ticks per food — realistic foraging effort.
#     "eat_gain": 0.25,
#     # init_food: 50x50 grid, 12 mothers, 1:1 food replacement.
#     # Humped curve: peak at 134 (EASY). 78 gives ~60% survival (BALANCED zone).
#     "init_food": 78,
#     "rest_recovery": 0.005,
#     **BASELINE_GENOME_WEIGHTS,
# }


# # ============================================================
# # Sensitivity sweep configuration
# # ============================================================

# SENSITIVITY_SWEEPS = {
#     # Set A (hunger_rate) REMOVED — hunger_rate is locked at 1/35 by starvation
#     # constraint (LOGIC.md Change J). It is a derived biological constant, not a
#     # free parameter. Sweeping it would violate the "no magic numbers" principle.
#     "B": {
#         "label": "move_cost",
#         "key": "move_cost",
#         "values": np.unique(
#             np.round(
#                 np.concatenate(
#                     [
#                         np.arange(0.0005, 0.001, 0.0002),
#                         np.arange(0.001, 0.0045, 0.0005),
#                         np.arange(0.005, 0.0086, 0.001),
#                     ]
#                 ),
#                 5,
#             )
#         ).tolist(),
#     },
#     "C": {
#         "label": "eat_gain",
#         "key": "eat_gain",
#         # rescaled from old range (0.03–0.155, for hunger_rate=0.005)
#         # to new range (0.10–0.50) appropriate for locked hunger_rate=0.0286.
#         # Ratio: eat_gain / hunger_rate = ticks of energy per food item.
#         # Target range: 3.5–17.5 ticks/food (sparse → generous nutritional value).
#         "values": np.unique(
#             np.round(
#                 np.concatenate(
#                     [
#                         np.arange(0.10, 0.15, 0.02),
#                         np.arange(0.15, 0.36, 0.01),
#                         np.arange(0.36, 0.52, 0.02),
#                     ]
#                 ),
#                 4,
#             )
#         ).tolist(),
#     },
#     "D": {
#         "label": "init_food",
#         "key": "init_food",
#         # 50x50 grid, initial_energy=1.0: ecological cliff ~100-175 (0-53% surv),
#         # BALANCED zone ~200-260 (65-83% surv), EASY zone ~300-450 (90%+ surv).
#         # Extended from 260 to 460 to characterize the full range.
#         "values": np.unique(
#             np.concatenate(
#                 [
#                     np.arange(30, 70, 10),
#                     np.arange(70, 200, 8),
#                     np.arange(200, 320, 15),
#                     np.arange(320, 470, 25),
#                 ]
#             ).astype(int)
#         ).tolist(),
#     },
#     "E": {
#         "label": "rest_recovery",
#         "key": "rest_recovery",
#         "values": list(np.round(np.arange(0.005, 0.111, 0.005), 4)),
#     },
# }


# SENSITIVITY_SUBPLOT_CONFIG = [
#     # Set A (hunger_rate) removed — locked parameter, not swept.
#     ("B", "move_cost", "Move Cost (per step)", "#5E81AC"),
#     ("C", "eat_gain", "Eat Gain (energy per food)", "#8FBCBB"),
#     ("D", "init_food", "Initial Food Count", "#D08770"),
#     ("E", "rest_recovery", "Rest Recovery (per tick)", "#B48EAD"),
# ]


# HIDE_BASELINE_FOR = {
#     "move_cost",
#     "eat_gain",
#     "init_food",
#     "rest_recovery",
# }


# # ============================================================
# # Baseline selection targets for run.py
# # ============================================================

# SELECTION_TARGETS = {
#     "balanced": {
#         # Mid-range survival: ~50-65% (food=78 zone, 1:1 replacement ecology).
#         # Energy is POPULATION-WEIGHTED: sum(alive energy) / init_mothers.
#         # At 60% survival × per-survivor energy ~0.38 → tail pop-weighted ≈ 0.20-0.28.
#         # Sort key prefers LOWER init_food so food=78 wins over food=100 (peak).
#         # NOTE: slope constraints REMOVED — 1:1 replacement causes inherent slow decline
#         # (pop_slope -0.005 to -0.015 is normal). Old constraints calibrated for stable
#         # batch-replenishment ecology; they excluded all non-peak food values.
#         "min_final_pop": 5.5,         # hard: >=46% survival — buffer for 15-seed variance
#         "energy_low": 0.18,           # pop-weighted lower bound
#         "energy_high": 0.38,          # pop-weighted upper bound
#         "target_energy": 0.25,
#         "max_tail_sd": 0.08,
#     },
#     "easy": {
#         # Peak survival zone: food=100 gives ~70-80% survival under 1:1 replacement.
#         # Pop-weighted tail energy at peak: ~0.29-0.33.
#         "min_final_pop": 7.5,         # hard: >=62% survival (7.5/12)
#         "min_energy": 0.22,           # pop-weighted lower bound
#         "target_energy": 0.30,
#         "max_tail_sd": 0.08,
#     },
#     "harsh": {
#         # Ecological stress: 10–33% survival (1.2–4/12).
#         # Pop-weighted tail energy: 10-25% survival × per-survivor energy → 0.03-0.12.
#         "min_final_pop": 1.2,         # hard: ≥10% survival (1.2/12)
#         "max_final_pop": 4.0,         # hard: ≤33% survival (4/12)
#         "energy_low": 0.02,           # pop-weighted lower bound
#         "energy_high": 0.20,          # pop-weighted upper bound
#         "target_pop": 3.0,
#         "target_energy": 0.08,
#     },
# }


# # ============================================================
# # Candidate grid for run.py baseline selection
# # ============================================================

# def candidate_configs(mode="sweep"):
#     """
#     Generate candidate parameter sets for run.py.

#     mode="single":
#         Runs one hand-picked configuration for detailed diagnostic plots.

#     mode="sweep":
#         11-point init_food grid (35–60). Covers the balanced→easy range.

#     mode="pipeline":
#         Not used — pipeline mode builds its sweep grid dynamically from
#         the OVAT-detected balanced baseline via _pipeline_sweep_configs().

#     Note:
#         BASELINE_GENOME_WEIGHTS are fixed here. Phase 2 is not evolving
#         weights yet; it only validates the ecological survival baseline
#         under neutral FORAGE/SELF weighting.
#     """
#     if mode == "single":
#         return [
#             {
#                 "perception_radius": DEFAULT_PERCEPTION_RADIUS,
#                 "hunger_rate": 1 / 35,   # locked by starvation constraint
#                 "move_cost": 0.001,
#                 "eat_gain": 0.25,        # root Config default for locked hunger_rate
#                 "init_food": 90,         # 50x50 grid, 12 mothers, initial_energy=1.0
#                 "rest_recovery": 0.005,
#                 **BASELINE_GENOME_WEIGHTS,
#                 "name": "single_test",
#             }
#         ]

#     # fmt: off
#     _GRIDS = {
#         "sweep": {
#             "hunger_rate":    [1 / 35],  # locked — not swept
#             "move_cost":      [0.001],
#             "eat_gain":       [0.25],
#             # init_food: 1:1 replacement creates a humped survival curve peaking
#             # at food=134. Above 134, FORAGE motivation dominates and agents
#             # starve holding food. Zones: HARSH=50, BALANCED=78-100, EASY=134.
#             # Values above 182 are excluded — they give LOWER survival than 134.
#             "init_food":      [50, 60, 78, 100, 134, 182],
#             "rest_recovery":  [0.005],
#         },
#         "pipeline": {
#             # hunger_rate removed — locked at 1/35 by starvation constraint.
#             # init_food shifted ~15% down vs 0.75 baseline.
#             "move_cost":     [0.0005, 0.001, 0.002, 0.003, 0.005, 0.007, 0.01, 0.03, 0.05, 0.1],
#             "eat_gain":      [0.10, 0.15, 0.20, 0.25, 0.30, 0.35, 0.40, 0.50, 0.75, 1.0],
#             "init_food":     [50, 75, 100, 125, 150, 175, 200, 250, 300, 350],
#             "rest_recovery": [0.005, 0.007, 0.008, 0.01, 0.015, 0.02, 0.03, 0.05, 0.07, 0.01],
#         },
#     }
#     # fmt: on

#     param_grid = _GRIDS.get(mode, _GRIDS["sweep"])

#     grid = {
#         "perception_radius": [DEFAULT_PERCEPTION_RADIUS],
#         **param_grid,
#         "care_weight":   [BASELINE_GENOME_WEIGHTS["care_weight"]],
#         "forage_weight": [BASELINE_GENOME_WEIGHTS["forage_weight"]],
#         "self_weight":   [BASELINE_GENOME_WEIGHTS["self_weight"]],
#     }

#     keys = list(grid.keys())
#     configs = []

#     for values in product(*[grid[k] for k in keys]):
#         params = dict(zip(keys, values))
#         params["name"] = "candidate"
#         configs.append(params)

#     return configs